#pragma once
#include"AXUtil.h"
#include "AXDevice.cuh"
#include"AXTexture.h"
#include"AXContext.h"
#include"AXChain.cuh"
#include"AXInputLayout.cuh"
#include"AXCommandList.h"
#include"AXRenderTargetView.cuh"
#include"AXView.h"
#include"AXBuffer.cuh"
#include"AXFormat.h"