#pragma once

enum eAXDimension
{
	// RTV
	AX_RTV_DIMENSION_BUFFER,
	AX_RTV_DIMENSION_TEXTURE2D,
	AX_RTV_DIMENSION_TEXTURE3D,

	// SRV
	AX_SRV_DIMENSION_BUFFER,
	AX_SRV_DIMENSION_TEXTURE2D,
	AX_SRV_DIMENSION_TEXTURE3D,
};